package com.fernjorie.taskmaster;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.UUID;

@DynamoDBTable(tableName = "TaskInfo")
public class TaskMaster {

    private String id;

    private String title;


    private String description;


    private String status;

    public TaskMaster(){}

    public TaskMaster(String title, String description) {
        this.title = title;
        this.description = description;
        this.status = "Available";
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey()
    public String getId() {
        return id;
    }


    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
